services:
  - type: web
    name: awaazflexibletimetable
    env: python
    buildCommand: pip install -r requirements.txt && ./setup_git.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: development
      - key: GIT_AUTO_PUSH
        value: true
      - key: ALLOW_GIT_IN_PRODUCTION
        value: true
      - key: GIT_USER_NAME
        value: perisri101
      - key: GIT_USER_EMAIL
        value: perisri101@gmail.com
      - key: GITHUB_TOKEN
        sync: false
      - key: GIT_REPOSITORY_URL
        value: https://github.com/perisri101/AwaazFlexibleTimeTable.git
      - key: GIT_BRANCH
        value: main
      - key: WEB_CONCURRENCY
        value: 4 